### ISSUE TITLE
KeyError at /complete/eveonline/

### ISSUE THREAD

**Issue by Bawbd** [skyride/avrse-auth#3]
Hello,

I'm running into an error after login and character authorization:

```
Internal Server Error: /complete/eveonline/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/social_django/utils.py", line 50, in wrapper
    return func(request, backend, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/social_django/views.py", line 32, in complete
    redirect_name=REDIRECT_FIELD_NAME, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/social_core/actions.py", line 41, in do_complete
    user = backend.complete(user=user, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/social_core/backends/base.py", line 40, in complete
    return self.auth_complete(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/social_core/utils.py", line 252, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/social_core/backends/oauth.py", line 398, in auth_complete
    *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/social_core/utils.py", line 252, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/social_core/backends/oauth.py", line 409, in do_auth
    return self.strategy.authenticate(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/social_django/strategy.py", line 115, in authenticate
    return authenticate(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 70, in authenticate
    user = _authenticate_with_backend(backend, backend_path, request, credentials)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 115, in _authenticate_with_backend
    return backend.authenticate(*args, **credentials)
  File "/usr/local/lib/python2.7/dist-packages/social_core/backends/base.py", line 80, in authenticate
    return self.pipeline(pipeline, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/social_core/backends/base.py", line 83, in pipeline
    out = self.run_pipeline(pipeline, pipeline_index, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/social_core/backends/base.py", line 108, in run_pipeline
    result = func(*args, **out) or {}
  File "/home/xxx/auth/eveauth/social_auth/pipeline.py", line 9, in update_user
    tasks.update_groups(user.id)
  File "/usr/local/lib/python2.7/dist-packages/celery/local.py", line 191, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py", line 380, in __call__
    return self.run(*args, **kwargs)
  File "/home/xxx/auth/eveauth/tasks.py", line 162, in update_groups
    if corp_id in members['corps'] or alliance_id in members['alliances'] or char_id in members['chars']:
KeyError: 'chars'
```
**Debug:**

> 
> Request Method: | GET
> Django version: 1.11.8
> KeyError
> 'chars'
> /home/xxx/auth/eveauth/tasks.py in update_groups, line 162
> Python Version: 2.7.13
> 

Any ideas?

**Comment by Bawbd** [comment]
Nevermind I found it, I had to update the config to add the chars line.
